# Generated by Django 4.2.25 on 2025-10-03 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShiftRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("line", "LINE"),
                            ("web", "Webダッシュボード"),
                            ("api", "API直接"),
                        ],
                        default="api",
                        max_length=20,
                    ),
                ),
                (
                    "source_user_id",
                    models.CharField(
                        help_text="LINEユーザーIDまたはWebユーザーID", max_length=255
                    ),
                ),
                ("staff_id", models.CharField(blank=True, max_length=50, null=True)),
                ("staff_name", models.CharField(blank=True, max_length=100, null=True)),
                ("target_month", models.CharField(help_text="YYYY-MM形式", max_length=7)),
                ("shift_data", models.JSONField(help_text="シフト希望の詳細データ")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "未処理"),
                            ("processed", "処理済み"),
                            ("approved", "承認済み"),
                            ("rejected", "却下"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "raw_payload",
                    models.JSONField(blank=True, help_text="元の生データ", null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=50)),
                ("endpoint", models.CharField(max_length=200)),
                ("method", models.CharField(max_length=10)),
                ("headers", models.JSONField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, null=True)),
                ("response_status", models.IntegerField(blank=True, null=True)),
                ("response_body", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StaffAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_id", models.CharField(max_length=50)),
                ("staff_name", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("available_from", models.TimeField(blank=True, null=True)),
                ("available_to", models.TimeField(blank=True, null=True)),
                (
                    "preference",
                    models.CharField(
                        choices=[
                            ("preferred", "希望"),
                            ("available", "可能"),
                            ("unavailable", "不可"),
                            ("off", "休み希望"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shift_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="gateway.shiftrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "staff_id"],
            },
        ),
        migrations.AddIndex(
            model_name="shiftrequest",
            index=models.Index(
                fields=["source", "status"], name="gateway_shi_source_2d9776_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shiftrequest",
            index=models.Index(
                fields=["staff_id", "target_month"],
                name="gateway_shi_staff_i_c6f2aa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="shiftrequest",
            index=models.Index(
                fields=["created_at"], name="gateway_shi_created_0d8cb5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffavailability",
            index=models.Index(
                fields=["staff_id", "date"], name="gateway_sta_staff_i_823eb4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffavailability",
            index=models.Index(
                fields=["date", "preference"], name="gateway_sta_date_246a49_idx"
            ),
        ),
    ]
